### ISSUE TITLE
Remove gitpod/local versions from all package.json(s) of all deepcase packages scripts

### ISSUE THREAD

**Issue by ivansglazunov** [deepcase/deepcase#15]
https://github.com/deepcase/deepcase/blob/749ca41061f3be4efd7f9a8ab2f91368699f331d/package.json#L12-L24

Realize some kind of precalculating gitpod env variable, and use it if exists.
Priority: .env, gitpod, default.

> All changes in PR.

**Comment by Konard** [comment]
What do you mean by "precalculating gitpod env"?

**Comment by ivansglazunov** [comment]
> What do you mean by "precalculating gitpod env"?

Before - cli commands already with gitpod config envs
After - universal cli commands, gitpod.yml adds config envs in global against predefined in package.json scripts envs
